# Generated by Django 4.0.4 on 2022-06-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inn', models.IntegerField()),
                ('ogrn', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='template_logo')),
                ('banner', models.ImageField(upload_to='template_banner')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.template')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='news_image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.site')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('kadastr_number', models.IntegerField()),
                ('building_year', models.IntegerField()),
                ('year_of_commissioning', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('room', models.IntegerField()),
                ('total_floor_space', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.company')),
            ],
        ),
    ]
