# Generated by Django 4.0.4 on 2022-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadastr_number', models.IntegerField()),
                ('building_year', models.IntegerField()),
                ('year_of_commissioning', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('room', models.IntegerField()),
                ('total_floor_space', models.IntegerField()),
            ],
        ),
    ]
