# Generated by Django 4.0.4 on 2022-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_company_template_site_news_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='template_banner'),
        ),
        migrations.AddField(
            model_name='site',
            name='bg_colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='template_logo'),
        ),
        migrations.AlterField(
            model_name='site',
            name='template',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
