# Generated by Django 4.0.4 on 2022-06-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_site_company_id_alter_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='company_id',
            new_name='company',
        ),
    ]
